### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by traderpedroso** [hapheus/n8n-nodes-duckduckgo#1]
i got it installed but not showing on webui any module duckduckgo

**Comment by hapheus** [comment]
<img width="383" alt="SCR-20240704-jyso" src="https://github.com/hapheus/n8n-nodes-duckduckgo/assets/837072/7e94aa0e-b82e-4884-8ebe-e8c8ee6ac7ab">

It should be available as **DuckDuckGo Node**. 
What version of node and n8n are you using?

**Comment by traderpedroso** [comment]
Sorry to bother you with such a silly question. I couldn't get it to appear in the editor, which is a bit more complicated to install in a cluster in queue mode, but I managed to install it locally until I figure out how to make it work in my cluster. 
 
thank you.
